version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=testdb
    depends_on:
      - mysql
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
